[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8

padding.x = 8
padding.y = 8

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
size = 11.0
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
